import { Download, RotateCcw, FileText, AlertTriangle, CheckCircle, XCircle } from 'lucide-react';

interface ClassificationReportProps {
  report: any;
  onRestart: () => void;
}

export default function ClassificationReport({ report, onRestart }: ClassificationReportProps) {
  if (!report) return null;

  const { overallClassification, evidenceSummary, exportJson, materialInfluence, profiling, article6Filter } = report;

  const badgeClass = overallClassification === 'high-risk' ? 'badge-red' : overallClassification === 'not-high-risk' ? 'badge-green' : 'badge-amber';
  const badgeText = overallClassification === 'high-risk' ? 'HIGH-RISK' : overallClassification === 'not-high-risk' ? 'NOT HIGH-RISK' : 'BORDERLINE';

  const handleExport = () => {
    const blob = new Blob([JSON.stringify(exportJson, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-risk-report-${report.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <div className="card text-center">
        <h3 className="card-title">Classification Report</h3>
        <div className={`badge ${badgeClass}`} style={{ fontSize: '1.25rem', padding: '0.75rem 1.5rem', marginBottom: '1rem' }}>
          {badgeText}
        </div>
        <p style={{ fontSize: '1.125rem', color: '#4b5563', marginBottom: '1.5rem' }}>
          Confidence: {evidenceSummary.overallConfidence}%
        </p>
        <div className="flex justify-between gap-4">
          <button className="btn btn-success" onClick={handleExport}>
            <Download size={18} /> Export JSON
          </button>
          <button className="btn btn-secondary" onClick={onRestart}>
            <RotateCcw size={18} /> New Assessment
          </button>
        </div>
      </div>

      <div className="card">
        <h3 className="card-title">Evidence Summary</h3>

        <div className="report-section">
          <h4 className="report-section-title">Annex III Triggers</h4>
          {evidenceSummary.annexIIITriggers.length > 0 ? (
            evidenceSummary.annexIIITriggers.map((trigger: string, i: number) => (
              <div key={i} className="flex items-center gap-2 mb-2">
                <AlertTriangle size={16} color="#F59E0B" />
                <span>{trigger}</span>
              </div>
            ))
          ) : (
            <p style={{ color: '#6b7280' }}>No Annex III use cases triggered.</p>
          )}
        </div>

        <div className="report-section">
          <h4 className="report-section-title">Material Influence</h4>
          <p>{evidenceSummary.materialInfluenceRationale}</p>
          <div className="score-bar mt-4">
            <div
              className={`score-bar-fill ${materialInfluence?.score <= 30 ? 'green' : materialInfluence?.score <= 50 ? 'amber' : 'red'}`}
              style={{ width: `${materialInfluence?.score || 0}%` }}
            />
          </div>
          <p className="text-center" style={{ fontSize: '0.875rem', color: '#6b7280' }}>
            Score: {materialInfluence?.score || 0}/100
          </p>
        </div>

        <div className="report-section">
          <h4 className="report-section-title">Profiling Status</h4>
          <div className="flex items-center gap-2">
            {profiling?.isProfiling ? (
              <>
                <XCircle size={20} color="#EF4444" />
                <span style={{ color: '#991b1b', fontWeight: 500 }}>{evidenceSummary.profilingStatus}</span>
              </>
            ) : (
              <>
                <CheckCircle size={20} color="#10B981" />
                <span style={{ color: '#065f46' }}>{evidenceSummary.profilingStatus}</span>
              </>
            )}
          </div>
        </div>

        <div className="report-section">
          <h4 className="report-section-title">Article 6(3) Filter</h4>
          <p>{evidenceSummary.article6Rationale}</p>
        </div>
      </div>

      <div className="card" style={{ background: '#fefce8', border: '1px solid #fde047' }}>
        <h3 className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <FileText size={20} />
          Recommendation
        </h3>
        <p style={{ fontSize: '0.9375rem', lineHeight: 1.6 }}>
          {article6Filter?.recommendation || 'Conduct further analysis to determine classification.'}
        </p>
        <p className="mt-4" style={{ fontSize: '0.8rem', color: '#6b7280', fontStyle: 'italic' }}>
          Disclaimer: This report is generated by automated analysis and does not constitute legal advice.
          Always consult qualified legal counsel for definitive classification under the EU AI Act.
        </p>
      </div>
    </div>
  );
}
