import { v4 as uuidv4 } from 'uuid';
import { ClassificationReport, SystemInput, AnnexIIIResult, MaterialInfluenceResult, ProfilingResult, Article6FilterResult } from './types';
import { classifyAnnexIII } from './annexiii';
import { scoreMaterialInfluence } from './materialInfluence';
import { detectProfiling } from './profiling';
import { evaluateArticle6Filter } from './article6filter';

function computeOverallClassification(
  annexIIIResults: AnnexIIIResult[],
  profiling: ProfilingResult,
  article6Filter: Article6FilterResult
): { classification: ClassificationReport['overallClassification']; confidence: number } {
  const anyAnnexIIITriggered = annexIIIResults.some(r => r.triggered && r.sector !== 'broad_marketing');
  const broadMarketingTriggered = annexIIIResults.some(r => r.sector === 'broad_marketing' && r.triggered);

  if (profiling.absoluteRedFlag || (anyAnnexIIITriggered && article6Filter.outcome === 'likely_high_risk')) {
    return { classification: 'high-risk', confidence: 85 };
  }
  if (broadMarketingTriggered && article6Filter.materialInfluenceExceeded) {
    return { classification: 'high-risk', confidence: 75 };
  }
  if (article6Filter.outcome === 'likely_high_risk') {
    return { classification: 'high-risk', confidence: 70 };
  }
  if (article6Filter.outcome === 'likely_exempt' && !anyAnnexIIITriggered) {
    return { classification: 'not-high-risk', confidence: 70 };
  }
  if (article6Filter.outcome === 'likely_exempt' && anyAnnexIIITriggered) {
    return { classification: 'borderline', confidence: 55 };
  }
  return { classification: 'borderline', confidence: 50 };
}

export function generateClassificationReport(input: SystemInput): ClassificationReport {
  const annexIIIResults = classifyAnnexIII(input);
  const materialInfluence = scoreMaterialInfluence(input);
  const profiling = detectProfiling(input);
  const article6Filter = evaluateArticle6Filter(input, materialInfluence, profiling);
  return buildReport(input, annexIIIResults, materialInfluence, profiling, article6Filter);
}

export function buildReport(
  input: SystemInput,
  annexIIIResults: AnnexIIIResult[],
  materialInfluence: MaterialInfluenceResult,
  profiling: ProfilingResult,
  article6Filter: Article6FilterResult
): ClassificationReport {
  const { classification: overallClassification, confidence: overallConfidence } = computeOverallClassification(
    annexIIIResults, profiling, article6Filter
  );

  const evidenceSummary = {
    annexIIITriggers: annexIIIResults.filter(r => r.triggered).map(r => `${r.sector}: ${r.useCase} (${r.confidenceScore}%)`),
    materialInfluenceRationale: materialInfluence.rationale,
    profilingStatus: profiling.isProfiling ? `Profiling detected: ${profiling.redFlags.join(', ')}` : 'No profiling detected',
    article6Rationale: article6Filter.rationale,
    overallConfidence
  };

  const id = uuidv4();

  const exportJson = {
    reportId: id,
    generatedAt: new Date().toISOString(),
    euAiActReference: 'Article 6 draft guidelines (May 2026)',
    systemName: input.systemName,
    classification: overallClassification,
    confidence: overallConfidence,
    annexIII: annexIIIResults,
    materialInfluenceScore: materialInfluence.score,
    profilingDetected: profiling.isProfiling,
    article6FilterOutcome: article6Filter.outcome,
    evidenceSummary,
    legalDisclaimer: 'This report is generated by automated analysis and does not constitute legal advice. Always consult qualified legal counsel for definitive classification.'
  };

  return {
    id,
    timestamp: exportJson.generatedAt,
    systemInput: input,
    overallClassification,
    annexIIIResults,
    materialInfluence,
    profiling,
    article6Filter,
    evidenceSummary,
    exportJson
  };
}
