import { ClassificationReport, SystemInput, AnnexIIIResult, MaterialInfluenceResult, ProfilingResult, Article6FilterResult } from '../types';
import { classifyAnnexIII } from './annexiii';
import { scoreMaterialInfluence } from './materialInfluence';
import { detectProfiling } from './profiling';
import { evaluateArticle6Filter } from './article6filter';
import { v4 as uuidv4 } from 'uuid';

export function generateClassificationReport(input: SystemInput): ClassificationReport {
  const annexIIIResults = classifyAnnexIII(input);
  const materialInfluence = scoreMaterialInfluence(input);
  const profiling = detectProfiling(input);
  const article6Filter = evaluateArticle6Filter(input, materialInfluence, profiling);

  // Determine overall classification
  let overallClassification: ClassificationReport['overallClassification'];
  let overallConfidence = 0;

  const anyAnnexIIITriggered = annexIIIResults.some(r => r.triggered && r.sector !== 'broad_marketing');
  const broadMarketingTriggered = annexIIIResults.some(r => r.sector === 'broad_marketing' && r.triggered);

  if (profiling.absoluteRedFlag || (anyAnnexIIITriggered && article6Filter.outcome === 'likely_high_risk')) {
    overallClassification = 'high-risk';
    overallConfidence = 85;
  } else if (broadMarketingTriggered && article6Filter.materialInfluenceExceeded) {
    overallClassification = 'high-risk';
    overallConfidence = 75;
  } else if (article6Filter.outcome === 'likely_high_risk') {
    overallClassification = 'high-risk';
    overallConfidence = 70;
  } else if (article6Filter.outcome === 'likely_exempt' && !anyAnnexIIITriggered) {
    overallClassification = 'not-high-risk';
    overallConfidence = 70;
  } else if (article6Filter.outcome === 'likely_exempt' && anyAnnexIIITriggered) {
    overallClassification = 'borderline';
    overallConfidence = 55;
  } else {
    overallClassification = 'borderline';
    overallConfidence = 50;
  }

  const evidenceSummary = {
    annexIIITriggers: annexIIIResults.filter(r => r.triggered).map(r => `${r.sector}: ${r.useCase} (${r.confidenceScore}%)`),
    materialInfluenceRationale: materialInfluence.rationale,
    profilingStatus: profiling.isProfiling ? `Profiling detected: ${profiling.redFlags.join(', ')}` : 'No profiling detected',
    article6Rationale: article6Filter.rationale,
    overallConfidence
  };

  const exportJson = {
    reportId: uuidv4(),
    generatedAt: new Date().toISOString(),
    euAiActReference: 'Article 6 draft guidelines (May 2026)',
    systemName: input.systemName,
    classification: overallClassification,
    confidence: overallConfidence,
    annexIII: annexIIIResults,
    materialInfluenceScore: materialInfluence.score,
    profilingDetected: profiling.isProfiling,
    article6FilterOutcome: article6Filter.outcome,
    evidenceSummary,
    legalDisclaimer: 'This report is generated by automated analysis and does not constitute legal advice. Always consult qualified legal counsel for definitive classification.'
  };

  return {
    id: exportJson.reportId,
    timestamp: exportJson.generatedAt,
    systemInput: input,
    overallClassification,
    annexIIIResults,
    materialInfluence,
    profiling,
    article6Filter,
    evidenceSummary,
    exportJson
  };
}
